// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleRpc

/// Response message for the Check method.
public struct CheckResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Operation is allowed when this field is not set. Any non-'OK' status
  /// indicates a denial; [google.rpc.Status.details][google.rpc.Status.details]
  /// would contain additional details about the denial.
  ///
  /// [google.rpc.Status.details]: https://www.google.com/search?q=Swift+google.rpc+GoogleRpc.Status/details
  public var status: GoogleRpc.Status? = nil

  /// Returns a set of request contexts generated from the `CheckRequest`.
  public var headers: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `CheckResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CheckResponse().with { $0.status = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v2.CheckResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
