// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Describes a resource referenced in the request.
public struct ResourceInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the resource referenced in the request.
  public var name: Swift.String = Swift.String()

  /// The resource type in the format of "{service}/{kind}".
  public var type: Swift.String = Swift.String()

  /// The resource permission needed for this request.
  /// The format must be "{service}/{plural}.{verb}".
  public var permission: Swift.String = Swift.String()

  /// Optional. The identifier of the container of this resource. For Google
  /// Cloud APIs, the resource container must be one of the following formats:
  ///     - `projects/<project-id or project-number>`
  ///     - `folders/<folder-number>`
  ///     - `organizations/<organization-number>`
  /// Required for the policy enforcement on the container level (e.g. VPCSC,
  /// Location Policy check, Org Policy check).
  public var container: Swift.String = Swift.String()

  /// Optional. The location of the resource, it must be a valid zone, region or
  /// multiregion, for example: "europe-west4", "northamerica-northeast1-a".
  /// Required for location policy check.
  public var location: Swift.String = Swift.String()

  /// Initialize a new instance of `ResourceInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResourceInfo().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicecontrol.v2.ResourceInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
