// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// [Service Control API
/// v2](https://cloud.google.com/service-infrastructure/docs/service-control/access-control)
///
/// This API provides admission control and telemetry reporting for services
/// that are integrated with [Service
/// Infrastructure](https://cloud.google.com/service-infrastructure).
///
/// @Snippet(path: "ServiceControllerQuickstart")
public final class ServiceControllerClient: Clients.ServiceControllerProtocol, Sendable {
  let inner: any Clients.ServiceControllerStub

  /// Creates a new `ServiceControllerClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ServiceControllerStub = try Clients.ServiceControllerTransport(options)
    inner = Clients.ServiceControllerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ServiceControllerLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// This method provides admission control for services that are integrated
  /// with [Service
  /// Infrastructure](https://cloud.google.com/service-infrastructure). It checks
  /// whether an operation should be allowed based on the service configuration
  /// and relevant policies. It must be called before the operation is executed.
  /// For more information, see
  /// [Admission
  /// Control](https://cloud.google.com/service-infrastructure/docs/admission-control).
  ///
  /// NOTE: The admission control has an expected policy propagation delay of
  /// 60s. The caller **must** not depend on the most recent policy changes.
  ///
  /// NOTE: The admission control has a hard limit of 1 referenced resources
  /// per call. If an operation refers to more than 1 resources, the caller
  /// must call the Check method multiple times.
  ///
  /// This method requires the `servicemanagement.services.check` permission
  /// on the specified service. For more information, see
  /// [Service Control API Access
  /// Control](https://cloud.google.com/service-infrastructure/docs/service-control/access-control).
  ///
  /// @Snippet(path: "ServiceController_Check")
  public func check(
    request: CheckRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiServiceControlV2.CheckResponse {
    try await self.inner.check(request: request, options: options)
  }

  /// This method provides telemetry reporting for services that are integrated
  /// with [Service
  /// Infrastructure](https://cloud.google.com/service-infrastructure). It
  /// reports a list of operations that have occurred on a service. It must be
  /// called after the operations have been executed. For more information, see
  /// [Telemetry
  /// Reporting](https://cloud.google.com/service-infrastructure/docs/telemetry-reporting).
  ///
  /// NOTE: The telemetry reporting has a hard limit of 100 operations and 1MB
  /// per Report call.
  ///
  /// This method requires the `servicemanagement.services.report` permission
  /// on the specified service. For more information, see
  /// [Service Control API Access
  /// Control](https://cloud.google.com/service-infrastructure/docs/service-control/access-control).
  ///
  /// @Snippet(path: "ServiceController_Report")
  public func report(
    request: ReportRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiServiceControlV2.ReportResponse {
    try await self.inner.report(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ServiceControllerClient`.
  ///
  /// To mock `ServiceControllerClient` change your functions to receive
  /// `some ServiceControllerProtocol` or `any ServiceControllerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ServiceControllerProtocol {
    /// See `ServiceControllerClient.check`.
    func check(request: CheckRequest) async throws -> GoogleApiServiceControlV2.CheckResponse

    /// See `ServiceControllerClient.report`.
    func report(request: ReportRequest) async throws -> GoogleApiServiceControlV2.ReportResponse

    /// See `ServiceControllerClient.check`.
    func check(
      request: CheckRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiServiceControlV2.CheckResponse

    /// See `ServiceControllerClient.report`.
    func report(
      request: ReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiServiceControlV2.ReportResponse
  }
}

// Default implementations
extension Clients.ServiceControllerProtocol {
  public func check(request: CheckRequest) async throws -> GoogleApiServiceControlV2.CheckResponse {
    try await self.check(request: request, options: .init())
  }

  public func check(
    request: CheckRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiServiceControlV2.CheckResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func report(request: ReportRequest) async throws
    -> GoogleApiServiceControlV2.ReportResponse
  {
    try await self.report(request: request, options: .init())
  }

  public func report(
    request: ReportRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleApiServiceControlV2.ReportResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
